### ISSUE TITLE
Android V2 embedding.

### ISSUE THREAD

**Issue by tudosxxx** [milanciganovic/instagram_share_plus#3]
The plugin `instagram_share_plus` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
Process finished with exit code 0

**Comment by aytunch** [comment]
This package does not work at the moment. Can you please upgrade the package according to android v2 embedding

**Comment by fabioselau077** [comment]
same problem, how to resolve?

**Comment by DennisAshford** [comment]
Has this been resolved? There currently doesn't seem to be a good package to share videos to instagram.

**Comment by milan-ciganovic** [comment]
[#4 ](https://github.com/milan-ciganovic/instagram_share_plus/pull/4)
